# Write results to output file -------------
WriteResultsToFile = function(result, dir, name) {
  file = file.path(dir, paste(name, '.txt', sep=""))
  sink(file)
  writeLines('Reference RFU')
  write.table(format(rbind(t(result$'Ref RAW'), result$'Ref, RFU'), digits=3, scientific = FALSE), sep = "\t", quote = F, col.names=NA)
  writeLines('Test RFU')
  write.table(format(rbind(t(result$'Test RAW'), result$'Test, RFU'), digits=3, scientific = FALSE), sep = "\t", quote = F, col.names=NA)
  writeLines('Reference model QC')
  write.table(format(result$`Ref, model QC`, digits=3, scientific = FALSE), col.names = F, sep = "\t", quote = F)
  writeLines('Test model QC')
  write.table(format(result$`Test, model QC`, digits=3, scientific = FALSE), col.names = F, sep = "\t", quote = F)
  writeLines('Parallelism F-Test')
  write.table(format(result$`Parallel test`$`F-Test`, digits=3, scientific = FALSE), col.names = F, sep = "\t", quote = F)
  writeLines('RP')
  write.table(format(result$RP, digits=3, scientific = FALSE), col.names = F, sep = "\t", quote = F)
  writeLines('Reference model coefficients')
  write.table(format(coef(result$'Ref model'), digits=3, scientific = FALSE), col.names = F, sep = "\t", quote = F)
  writeLines('Test model coefficients')
  write.table(format(coef(result$'Test model'), digits=3, scientific = FALSE), col.names = F, sep = "\t", quote = F)
  sink()
  p <- model.multiple.point.ggplot(result$'Ref model', result$'Ref, df', result$'Test model', result$'Test, df')
  ggsave(plot=p, file.path(dir, paste(name, '_mp_model.png', sep="")), width = 7, height = 7, units="in")
  p <- model.single.point.ggplot(result$'Ref model', result$'Ref, df', result$'Test model', result$'Test, df')
  ggsave(plot=p, file.path(dir, paste(name, '_sp_model.png', sep="")), width = 7, height = 7, units="in")
  p <- model.boxplot.ggplot(result$'Ref model', result$'Ref, df', result$'Test model', result$'Test, df')
  ggsave(plot=p, file.path(dir, paste(name, '_boxes.png', sep="")), width = 7, height = 7, units="in")
  T
}
